export type Neighborhood = {
    id: string
    name: string
    price: number
}

export const NEIGHBORHOODS: Neighborhood[] = [
    { id: "goztepe-mh", name: "Göztepe Mh.", price: 0 },
    { id: "gulluk-mh", name: "Güllük Mh.", price: 0 },
    { id: "gultepe-mh", name: "Gültepe Mh.", price: 50 },
    { id: "gundogdu-mh", name: "Gündoğdu Mh.", price: 70 },
    { id: "hacialibey-mh", name: "Hacıalibey Mh.", price: 0 },
    { id: "hacisiyet-mh", name: "Hacısiyet Mh.", price: 0 },
    { id: "hayriye-mh", name: "Hayriye Mh.", price: 0 },
    { id: "hosnudiye-mh", name: "Hoşnudiye Mh.", price: 0 },
    { id: "huzur-mh", name: "Huzur Mh.", price: 50 },
    { id: "ihlamurkent", name: "Ihlamurkent", price: 70 },
    { id: "isiklar-mh", name: "Işıklar Mh.", price: 0 },
    { id: "ihsaniye-mh", name: "İhsaniye Mh.", price: 0 },
    { id: "imsehir-organize-sanayi", name: "İmişehir Organize Sanayi", price: 250 },
    { id: "inonu-mah", name: "İnönü mah.", price: 500 },
    { id: "istiklal-mah", name: "İstiklal mah.", price: 0 },
    { id: "karabayir-bag", name: "Karabayır bağ.", price: 100 },
    { id: "camlica", name: "Çamlıca", price: 50 },
    { id: "cankaya-mh", name: "Çankaya Mh.", price: 50 },
    { id: "cukurhisar", name: "Çukurhisar", price: 300 },
    { id: "dede-mh", name: "Dede mh.", price: 0 },
    { id: "deliklitas", name: "Deliklitaş", price: 0 },
    { id: "dumlupinar-kyk", name: "Dumlupınar kyk", price: 50 },
    { id: "emek-mh", name: "Emek Mh.", price: 50 },
    { id: "erenkoy-mh", name: "Erenköy Mh.", price: 50 },
    { id: "ertugrulgazi-mh", name: "Ertuğrulgazi Mh.", price: 0 },
    { id: "esentepe-mh", name: "Esentepe Mh.", price: 50 },
    { id: "eskibaglar-mh", name: "Eskibağlar mh.", price: 0 },
    { id: "fatih-mh", name: "Fatih mh.", price: 0 },
    { id: "fevzi-cakmak-mh", name: "Fevzi Çakmak Mh.", price: 50 },
    { id: "gaffar-okkan-cd", name: "Gaffar Okkan Cd.", price: 0 },
    { id: "gocmen-evleri", name: "Göçmen Evleri", price: 70 },
    { id: "gokmeydan-mh", name: "Gökmeydan Mh.", price: 0 },
    { id: "61-evler", name: "61 Evler", price: 0 },
    { id: "71-evler", name: "71 Evler", price: 100 },
    { id: "75-yil-mah", name: "75. yıl mah.", price: 250 },
    { id: "akarbasi-mah", name: "Akarbaşı mah.", price: 0 },
    { id: "akcami-mh", name: "Akcami mh.", price: 0 },
    { id: "anadolu-univ-civari", name: "Anadolu Ü. Civarı", price: 0 },
    { id: "anemon-otel", name: "Anemon otel", price: 0 },
    { id: "arifiye-mah", name: "Arifiye mah.", price: 0 },
    { id: "asagi-sogutonu", name: "Aşağı Söğütönü", price: 100 },
    { id: "ataturk-bulvari", name: "Atatürk Bulvarı", price: 0 },
    { id: "atayurt-okullari", name: "Atayurt okulları", price: 100 },
    { id: "bahcelievler", name: "Bahçelievler", price: 0 },
    { id: "baksan", name: "Baksan", price: 0 },
    { id: "batikent", name: "Batıkent", price: 70 },
    { id: "besevler-mh", name: "Beşevler Mh.", price: 0 },
    { id: "bursa-yolu", name: "Bursa Yolu", price: 100 },
    { id: "buyukdere", name: "Büyükdere", price: 0 },
    { id: "cumhuriye-mh", name: "Cumhuriye Mh.", price: 0 },
    { id: "cunudiye-mh", name: "Cunudiye Mh.", price: 0 },
    { id: "kirmizitoprak-mh", name: "Kırmızıtoprak Mh.", price: 0 },
    { id: "kizilcikli-mp-cd", name: "Kızılcıklı MP Cd.", price: 0 },
    { id: "koprubasi", name: "Köprübaşı", price: 0 },
    { id: "kumlubel", name: "Kumlubel", price: 0 },
    { id: "kurtulus-mah", name: "Kurtuluş mah.", price: 0 },
    { id: "kuyubasi-mh", name: "Kuyubaşı Mh.", price: 50 },
    { id: "kume-evleri", name: "Küme Evleri", price: 50 },
    { id: "kutahya-yolu", name: "Kütahya yolu", price: 150 },
    { id: "mamure-mh", name: "Mamure mh.", price: 0 },
    { id: "merkez", name: "Merkez", price: 0 },
    { id: "mustafa-kemal-pasa-mh", name: "Mustafa Kemal Paşa Mh.", price: 0 },
    { id: "muttalip-cd", name: "Muttalip Cd.", price: 0 },
    { id: "muttalip-mahallesi", name: "Muttalip Mahallesi", price: 150 },
    { id: "organize-san", name: "Organize san.", price: 250 },
    { id: "orhangazi-mh", name: "Orhangazi Mh.", price: 100 },
    { id: "orta-mh", name: "Orta mh.", price: 100 },
    { id: "osmangazi-mh", name: "Osmangazi Mh.", price: 0 },
    { id: "osmangazi-univ", name: "Osmangazi üniv", price: 50 },
    { id: "omeraga-mh", name: "Ömerağa Mh.", price: 0 },
    { id: "omur-mh", name: "Ömür Mh.", price: 100 },
    { id: "radar-mh", name: "Radar Mh.", price: 50 },
    { id: "raykent", name: "Raykent", price: 0 },
    { id: "rixos-otel", name: "Rixos otel", price: 50 },
    { id: "sakarya-cd", name: "Sakarya Cd.", price: 0 },
    { id: "sakintepe-mh", name: "Sakintepe Mh.", price: 200 },
    { id: "sazova-mh", name: "Sazova Mh.", price: 60 },
    { id: "siraevler", name: "Sıraevler", price: 40 },
    { id: "sivrihisar", name: "Sivrihisar", price: 120 },
    { id: "sivrihisar-cd", name: "Sivrihisar Cd.", price: 0 },
    { id: "sultandere", name: "Sultandere", price: 200 },
    { id: "sumer-mh", name: "Sümer Mh.", price: 0 },
    { id: "sutluce-mh", name: "Sütlüce Mh.", price: 30 },
    { id: "sarhoyuk-mh", name: "Şarhöyük Mh.", price: 30 },
    { id: "sarkiye-mh", name: "Şarkiye mh.", price: 0 },
    { id: "seker-mh", name: "Şeker mh.", price: 0 },
    { id: "sirintepe-mh", name: "Şirintepe Mh.", price: 50 },
    { id: "takkali-mah", name: "Takkalı mah.", price: 70 },
    { id: "ted-koleji", name: "Ted koleji", price: 150 },
    { id: "teksan", name: "Teksan", price: 250 },
    { id: "terzievleri", name: "Terzievleri", price: 50 },
    { id: "tunali-mh", name: "Tunalı Mh.", price: 0 },
    { id: "uluonder-mh", name: "Uluönder Mh.", price: 0 },
    { id: "universite-evleri", name: "Üniversite Evleri", price: 50 },
    { id: "vadisehir", name: "Vadişehir", price: 70 },
    { id: "vatan-cd", name: "Vatan Cd.", price: 0 },
    { id: "visnelik-mh", name: "Vişnelik Mh.", price: 0 },
    { id: "yeni-baglar-mh", name: "Yeni Bağlar Mh.", price: 0 },
    { id: "yeni-mh", name: "Yeni Mh.", price: 0 },
    { id: "yenidogan-mh", name: "Yenidoğan Mh.", price: 50 },
    { id: "yenikent", name: "Yenikent", price: 0 },
    { id: "yenisehir-konaklari", name: "Yenişehir konakları", price: 250 },
    { id: "yesiltepe-mh", name: "Yeşiltepe Mh.", price: 50 },
    { id: "yildiztepe-mh", name: "Yıldıztepe Mh.", price: 0 },
    { id: "yukari-sogutonu", name: "Yukarı Söğütönü", price: 150 },
    { id: "yunuskent", name: "Yunuskent", price: 0 },
    { id: "zafer-mh", name: "Zafer Mh.", price: 0 },
    { id: "zincirlikuyu-mh", name: "Zincirlikuyu Mh.", price: 100 }
];

export default NEIGHBORHOODS;